/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.steam.thrift.DataHanding;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-07-27")
public class Game implements org.apache.thrift.TBase<Game, Game._Fields>, java.io.Serializable, Cloneable, Comparable<Game> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Game");

  private static final org.apache.thrift.protocol.TField GAME_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("gameId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField GAME_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("gameName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField COMMENTS_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("commentsNum", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField LIKE_RATE_FIELD_DESC = new org.apache.thrift.protocol.TField("LikeRate", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField DISCOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("discount", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField PRICE_FIELD_DESC = new org.apache.thrift.protocol.TField("price", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField IMG_FIELD_DESC = new org.apache.thrift.protocol.TField("img", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField OUT_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("outDate", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField DEVELOPERS_FIELD_DESC = new org.apache.thrift.protocol.TField("Developers", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField DIY_LABELS_FIELD_DESC = new org.apache.thrift.protocol.TField("diyLabels", org.apache.thrift.protocol.TType.STRING, (short)10);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new GameStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new GameTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String gameId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String gameName; // required
  public int commentsNum; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String LikeRate; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String discount; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String price; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String img; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String outDate; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String Developers; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String diyLabels; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GAME_ID((short)1, "gameId"),
    GAME_NAME((short)2, "gameName"),
    COMMENTS_NUM((short)3, "commentsNum"),
    LIKE_RATE((short)4, "LikeRate"),
    DISCOUNT((short)5, "discount"),
    PRICE((short)6, "price"),
    IMG((short)7, "img"),
    OUT_DATE((short)8, "outDate"),
    DEVELOPERS((short)9, "Developers"),
    DIY_LABELS((short)10, "diyLabels");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GAME_ID
          return GAME_ID;
        case 2: // GAME_NAME
          return GAME_NAME;
        case 3: // COMMENTS_NUM
          return COMMENTS_NUM;
        case 4: // LIKE_RATE
          return LIKE_RATE;
        case 5: // DISCOUNT
          return DISCOUNT;
        case 6: // PRICE
          return PRICE;
        case 7: // IMG
          return IMG;
        case 8: // OUT_DATE
          return OUT_DATE;
        case 9: // DEVELOPERS
          return DEVELOPERS;
        case 10: // DIY_LABELS
          return DIY_LABELS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __COMMENTSNUM_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GAME_ID, new org.apache.thrift.meta_data.FieldMetaData("gameId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GAME_NAME, new org.apache.thrift.meta_data.FieldMetaData("gameName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COMMENTS_NUM, new org.apache.thrift.meta_data.FieldMetaData("commentsNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LIKE_RATE, new org.apache.thrift.meta_data.FieldMetaData("LikeRate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISCOUNT, new org.apache.thrift.meta_data.FieldMetaData("discount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRICE, new org.apache.thrift.meta_data.FieldMetaData("price", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IMG, new org.apache.thrift.meta_data.FieldMetaData("img", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OUT_DATE, new org.apache.thrift.meta_data.FieldMetaData("outDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEVELOPERS, new org.apache.thrift.meta_data.FieldMetaData("Developers", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DIY_LABELS, new org.apache.thrift.meta_data.FieldMetaData("diyLabels", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Game.class, metaDataMap);
  }

  public Game() {
  }

  public Game(
    java.lang.String gameId,
    java.lang.String gameName,
    int commentsNum,
    java.lang.String LikeRate,
    java.lang.String discount,
    java.lang.String price,
    java.lang.String img,
    java.lang.String outDate,
    java.lang.String Developers,
    java.lang.String diyLabels)
  {
    this();
    this.gameId = gameId;
    this.gameName = gameName;
    this.commentsNum = commentsNum;
    setCommentsNumIsSet(true);
    this.LikeRate = LikeRate;
    this.discount = discount;
    this.price = price;
    this.img = img;
    this.outDate = outDate;
    this.Developers = Developers;
    this.diyLabels = diyLabels;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Game(Game other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetGameId()) {
      this.gameId = other.gameId;
    }
    if (other.isSetGameName()) {
      this.gameName = other.gameName;
    }
    this.commentsNum = other.commentsNum;
    if (other.isSetLikeRate()) {
      this.LikeRate = other.LikeRate;
    }
    if (other.isSetDiscount()) {
      this.discount = other.discount;
    }
    if (other.isSetPrice()) {
      this.price = other.price;
    }
    if (other.isSetImg()) {
      this.img = other.img;
    }
    if (other.isSetOutDate()) {
      this.outDate = other.outDate;
    }
    if (other.isSetDevelopers()) {
      this.Developers = other.Developers;
    }
    if (other.isSetDiyLabels()) {
      this.diyLabels = other.diyLabels;
    }
  }

  public Game deepCopy() {
    return new Game(this);
  }

  @Override
  public void clear() {
    this.gameId = null;
    this.gameName = null;
    setCommentsNumIsSet(false);
    this.commentsNum = 0;
    this.LikeRate = null;
    this.discount = null;
    this.price = null;
    this.img = null;
    this.outDate = null;
    this.Developers = null;
    this.diyLabels = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getGameId() {
    return this.gameId;
  }

  public Game setGameId(@org.apache.thrift.annotation.Nullable java.lang.String gameId) {
    this.gameId = gameId;
    return this;
  }

  public void unsetGameId() {
    this.gameId = null;
  }

  /** Returns true if field gameId is set (has been assigned a value) and false otherwise */
  public boolean isSetGameId() {
    return this.gameId != null;
  }

  public void setGameIdIsSet(boolean value) {
    if (!value) {
      this.gameId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getGameName() {
    return this.gameName;
  }

  public Game setGameName(@org.apache.thrift.annotation.Nullable java.lang.String gameName) {
    this.gameName = gameName;
    return this;
  }

  public void unsetGameName() {
    this.gameName = null;
  }

  /** Returns true if field gameName is set (has been assigned a value) and false otherwise */
  public boolean isSetGameName() {
    return this.gameName != null;
  }

  public void setGameNameIsSet(boolean value) {
    if (!value) {
      this.gameName = null;
    }
  }

  public int getCommentsNum() {
    return this.commentsNum;
  }

  public Game setCommentsNum(int commentsNum) {
    this.commentsNum = commentsNum;
    setCommentsNumIsSet(true);
    return this;
  }

  public void unsetCommentsNum() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __COMMENTSNUM_ISSET_ID);
  }

  /** Returns true if field commentsNum is set (has been assigned a value) and false otherwise */
  public boolean isSetCommentsNum() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __COMMENTSNUM_ISSET_ID);
  }

  public void setCommentsNumIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __COMMENTSNUM_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getLikeRate() {
    return this.LikeRate;
  }

  public Game setLikeRate(@org.apache.thrift.annotation.Nullable java.lang.String LikeRate) {
    this.LikeRate = LikeRate;
    return this;
  }

  public void unsetLikeRate() {
    this.LikeRate = null;
  }

  /** Returns true if field LikeRate is set (has been assigned a value) and false otherwise */
  public boolean isSetLikeRate() {
    return this.LikeRate != null;
  }

  public void setLikeRateIsSet(boolean value) {
    if (!value) {
      this.LikeRate = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDiscount() {
    return this.discount;
  }

  public Game setDiscount(@org.apache.thrift.annotation.Nullable java.lang.String discount) {
    this.discount = discount;
    return this;
  }

  public void unsetDiscount() {
    this.discount = null;
  }

  /** Returns true if field discount is set (has been assigned a value) and false otherwise */
  public boolean isSetDiscount() {
    return this.discount != null;
  }

  public void setDiscountIsSet(boolean value) {
    if (!value) {
      this.discount = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPrice() {
    return this.price;
  }

  public Game setPrice(@org.apache.thrift.annotation.Nullable java.lang.String price) {
    this.price = price;
    return this;
  }

  public void unsetPrice() {
    this.price = null;
  }

  /** Returns true if field price is set (has been assigned a value) and false otherwise */
  public boolean isSetPrice() {
    return this.price != null;
  }

  public void setPriceIsSet(boolean value) {
    if (!value) {
      this.price = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getImg() {
    return this.img;
  }

  public Game setImg(@org.apache.thrift.annotation.Nullable java.lang.String img) {
    this.img = img;
    return this;
  }

  public void unsetImg() {
    this.img = null;
  }

  /** Returns true if field img is set (has been assigned a value) and false otherwise */
  public boolean isSetImg() {
    return this.img != null;
  }

  public void setImgIsSet(boolean value) {
    if (!value) {
      this.img = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOutDate() {
    return this.outDate;
  }

  public Game setOutDate(@org.apache.thrift.annotation.Nullable java.lang.String outDate) {
    this.outDate = outDate;
    return this;
  }

  public void unsetOutDate() {
    this.outDate = null;
  }

  /** Returns true if field outDate is set (has been assigned a value) and false otherwise */
  public boolean isSetOutDate() {
    return this.outDate != null;
  }

  public void setOutDateIsSet(boolean value) {
    if (!value) {
      this.outDate = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDevelopers() {
    return this.Developers;
  }

  public Game setDevelopers(@org.apache.thrift.annotation.Nullable java.lang.String Developers) {
    this.Developers = Developers;
    return this;
  }

  public void unsetDevelopers() {
    this.Developers = null;
  }

  /** Returns true if field Developers is set (has been assigned a value) and false otherwise */
  public boolean isSetDevelopers() {
    return this.Developers != null;
  }

  public void setDevelopersIsSet(boolean value) {
    if (!value) {
      this.Developers = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDiyLabels() {
    return this.diyLabels;
  }

  public Game setDiyLabels(@org.apache.thrift.annotation.Nullable java.lang.String diyLabels) {
    this.diyLabels = diyLabels;
    return this;
  }

  public void unsetDiyLabels() {
    this.diyLabels = null;
  }

  /** Returns true if field diyLabels is set (has been assigned a value) and false otherwise */
  public boolean isSetDiyLabels() {
    return this.diyLabels != null;
  }

  public void setDiyLabelsIsSet(boolean value) {
    if (!value) {
      this.diyLabels = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case GAME_ID:
      if (value == null) {
        unsetGameId();
      } else {
        setGameId((java.lang.String)value);
      }
      break;

    case GAME_NAME:
      if (value == null) {
        unsetGameName();
      } else {
        setGameName((java.lang.String)value);
      }
      break;

    case COMMENTS_NUM:
      if (value == null) {
        unsetCommentsNum();
      } else {
        setCommentsNum((java.lang.Integer)value);
      }
      break;

    case LIKE_RATE:
      if (value == null) {
        unsetLikeRate();
      } else {
        setLikeRate((java.lang.String)value);
      }
      break;

    case DISCOUNT:
      if (value == null) {
        unsetDiscount();
      } else {
        setDiscount((java.lang.String)value);
      }
      break;

    case PRICE:
      if (value == null) {
        unsetPrice();
      } else {
        setPrice((java.lang.String)value);
      }
      break;

    case IMG:
      if (value == null) {
        unsetImg();
      } else {
        setImg((java.lang.String)value);
      }
      break;

    case OUT_DATE:
      if (value == null) {
        unsetOutDate();
      } else {
        setOutDate((java.lang.String)value);
      }
      break;

    case DEVELOPERS:
      if (value == null) {
        unsetDevelopers();
      } else {
        setDevelopers((java.lang.String)value);
      }
      break;

    case DIY_LABELS:
      if (value == null) {
        unsetDiyLabels();
      } else {
        setDiyLabels((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case GAME_ID:
      return getGameId();

    case GAME_NAME:
      return getGameName();

    case COMMENTS_NUM:
      return getCommentsNum();

    case LIKE_RATE:
      return getLikeRate();

    case DISCOUNT:
      return getDiscount();

    case PRICE:
      return getPrice();

    case IMG:
      return getImg();

    case OUT_DATE:
      return getOutDate();

    case DEVELOPERS:
      return getDevelopers();

    case DIY_LABELS:
      return getDiyLabels();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case GAME_ID:
      return isSetGameId();
    case GAME_NAME:
      return isSetGameName();
    case COMMENTS_NUM:
      return isSetCommentsNum();
    case LIKE_RATE:
      return isSetLikeRate();
    case DISCOUNT:
      return isSetDiscount();
    case PRICE:
      return isSetPrice();
    case IMG:
      return isSetImg();
    case OUT_DATE:
      return isSetOutDate();
    case DEVELOPERS:
      return isSetDevelopers();
    case DIY_LABELS:
      return isSetDiyLabels();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Game)
      return this.equals((Game)that);
    return false;
  }

  public boolean equals(Game that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_gameId = true && this.isSetGameId();
    boolean that_present_gameId = true && that.isSetGameId();
    if (this_present_gameId || that_present_gameId) {
      if (!(this_present_gameId && that_present_gameId))
        return false;
      if (!this.gameId.equals(that.gameId))
        return false;
    }

    boolean this_present_gameName = true && this.isSetGameName();
    boolean that_present_gameName = true && that.isSetGameName();
    if (this_present_gameName || that_present_gameName) {
      if (!(this_present_gameName && that_present_gameName))
        return false;
      if (!this.gameName.equals(that.gameName))
        return false;
    }

    boolean this_present_commentsNum = true;
    boolean that_present_commentsNum = true;
    if (this_present_commentsNum || that_present_commentsNum) {
      if (!(this_present_commentsNum && that_present_commentsNum))
        return false;
      if (this.commentsNum != that.commentsNum)
        return false;
    }

    boolean this_present_LikeRate = true && this.isSetLikeRate();
    boolean that_present_LikeRate = true && that.isSetLikeRate();
    if (this_present_LikeRate || that_present_LikeRate) {
      if (!(this_present_LikeRate && that_present_LikeRate))
        return false;
      if (!this.LikeRate.equals(that.LikeRate))
        return false;
    }

    boolean this_present_discount = true && this.isSetDiscount();
    boolean that_present_discount = true && that.isSetDiscount();
    if (this_present_discount || that_present_discount) {
      if (!(this_present_discount && that_present_discount))
        return false;
      if (!this.discount.equals(that.discount))
        return false;
    }

    boolean this_present_price = true && this.isSetPrice();
    boolean that_present_price = true && that.isSetPrice();
    if (this_present_price || that_present_price) {
      if (!(this_present_price && that_present_price))
        return false;
      if (!this.price.equals(that.price))
        return false;
    }

    boolean this_present_img = true && this.isSetImg();
    boolean that_present_img = true && that.isSetImg();
    if (this_present_img || that_present_img) {
      if (!(this_present_img && that_present_img))
        return false;
      if (!this.img.equals(that.img))
        return false;
    }

    boolean this_present_outDate = true && this.isSetOutDate();
    boolean that_present_outDate = true && that.isSetOutDate();
    if (this_present_outDate || that_present_outDate) {
      if (!(this_present_outDate && that_present_outDate))
        return false;
      if (!this.outDate.equals(that.outDate))
        return false;
    }

    boolean this_present_Developers = true && this.isSetDevelopers();
    boolean that_present_Developers = true && that.isSetDevelopers();
    if (this_present_Developers || that_present_Developers) {
      if (!(this_present_Developers && that_present_Developers))
        return false;
      if (!this.Developers.equals(that.Developers))
        return false;
    }

    boolean this_present_diyLabels = true && this.isSetDiyLabels();
    boolean that_present_diyLabels = true && that.isSetDiyLabels();
    if (this_present_diyLabels || that_present_diyLabels) {
      if (!(this_present_diyLabels && that_present_diyLabels))
        return false;
      if (!this.diyLabels.equals(that.diyLabels))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetGameId()) ? 131071 : 524287);
    if (isSetGameId())
      hashCode = hashCode * 8191 + gameId.hashCode();

    hashCode = hashCode * 8191 + ((isSetGameName()) ? 131071 : 524287);
    if (isSetGameName())
      hashCode = hashCode * 8191 + gameName.hashCode();

    hashCode = hashCode * 8191 + commentsNum;

    hashCode = hashCode * 8191 + ((isSetLikeRate()) ? 131071 : 524287);
    if (isSetLikeRate())
      hashCode = hashCode * 8191 + LikeRate.hashCode();

    hashCode = hashCode * 8191 + ((isSetDiscount()) ? 131071 : 524287);
    if (isSetDiscount())
      hashCode = hashCode * 8191 + discount.hashCode();

    hashCode = hashCode * 8191 + ((isSetPrice()) ? 131071 : 524287);
    if (isSetPrice())
      hashCode = hashCode * 8191 + price.hashCode();

    hashCode = hashCode * 8191 + ((isSetImg()) ? 131071 : 524287);
    if (isSetImg())
      hashCode = hashCode * 8191 + img.hashCode();

    hashCode = hashCode * 8191 + ((isSetOutDate()) ? 131071 : 524287);
    if (isSetOutDate())
      hashCode = hashCode * 8191 + outDate.hashCode();

    hashCode = hashCode * 8191 + ((isSetDevelopers()) ? 131071 : 524287);
    if (isSetDevelopers())
      hashCode = hashCode * 8191 + Developers.hashCode();

    hashCode = hashCode * 8191 + ((isSetDiyLabels()) ? 131071 : 524287);
    if (isSetDiyLabels())
      hashCode = hashCode * 8191 + diyLabels.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Game other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetGameId()).compareTo(other.isSetGameId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGameId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gameId, other.gameId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGameName()).compareTo(other.isSetGameName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGameName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gameName, other.gameName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCommentsNum()).compareTo(other.isSetCommentsNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommentsNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commentsNum, other.commentsNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLikeRate()).compareTo(other.isSetLikeRate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLikeRate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.LikeRate, other.LikeRate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDiscount()).compareTo(other.isSetDiscount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDiscount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.discount, other.discount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPrice()).compareTo(other.isSetPrice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrice()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.price, other.price);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetImg()).compareTo(other.isSetImg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.img, other.img);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOutDate()).compareTo(other.isSetOutDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outDate, other.outDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDevelopers()).compareTo(other.isSetDevelopers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDevelopers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Developers, other.Developers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDiyLabels()).compareTo(other.isSetDiyLabels());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDiyLabels()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.diyLabels, other.diyLabels);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Game(");
    boolean first = true;

    sb.append("gameId:");
    if (this.gameId == null) {
      sb.append("null");
    } else {
      sb.append(this.gameId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("gameName:");
    if (this.gameName == null) {
      sb.append("null");
    } else {
      sb.append(this.gameName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("commentsNum:");
    sb.append(this.commentsNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("LikeRate:");
    if (this.LikeRate == null) {
      sb.append("null");
    } else {
      sb.append(this.LikeRate);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("discount:");
    if (this.discount == null) {
      sb.append("null");
    } else {
      sb.append(this.discount);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("price:");
    if (this.price == null) {
      sb.append("null");
    } else {
      sb.append(this.price);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("img:");
    if (this.img == null) {
      sb.append("null");
    } else {
      sb.append(this.img);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("outDate:");
    if (this.outDate == null) {
      sb.append("null");
    } else {
      sb.append(this.outDate);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Developers:");
    if (this.Developers == null) {
      sb.append("null");
    } else {
      sb.append(this.Developers);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("diyLabels:");
    if (this.diyLabels == null) {
      sb.append("null");
    } else {
      sb.append(this.diyLabels);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GameStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public GameStandardScheme getScheme() {
      return new GameStandardScheme();
    }
  }

  private static class GameStandardScheme extends org.apache.thrift.scheme.StandardScheme<Game> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Game struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GAME_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.gameId = iprot.readString();
              struct.setGameIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // GAME_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.gameName = iprot.readString();
              struct.setGameNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // COMMENTS_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.commentsNum = iprot.readI32();
              struct.setCommentsNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LIKE_RATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.LikeRate = iprot.readString();
              struct.setLikeRateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // DISCOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.discount = iprot.readString();
              struct.setDiscountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // PRICE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.price = iprot.readString();
              struct.setPriceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // IMG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.img = iprot.readString();
              struct.setImgIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // OUT_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.outDate = iprot.readString();
              struct.setOutDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // DEVELOPERS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Developers = iprot.readString();
              struct.setDevelopersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // DIY_LABELS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.diyLabels = iprot.readString();
              struct.setDiyLabelsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Game struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.gameId != null) {
        oprot.writeFieldBegin(GAME_ID_FIELD_DESC);
        oprot.writeString(struct.gameId);
        oprot.writeFieldEnd();
      }
      if (struct.gameName != null) {
        oprot.writeFieldBegin(GAME_NAME_FIELD_DESC);
        oprot.writeString(struct.gameName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(COMMENTS_NUM_FIELD_DESC);
      oprot.writeI32(struct.commentsNum);
      oprot.writeFieldEnd();
      if (struct.LikeRate != null) {
        oprot.writeFieldBegin(LIKE_RATE_FIELD_DESC);
        oprot.writeString(struct.LikeRate);
        oprot.writeFieldEnd();
      }
      if (struct.discount != null) {
        oprot.writeFieldBegin(DISCOUNT_FIELD_DESC);
        oprot.writeString(struct.discount);
        oprot.writeFieldEnd();
      }
      if (struct.price != null) {
        oprot.writeFieldBegin(PRICE_FIELD_DESC);
        oprot.writeString(struct.price);
        oprot.writeFieldEnd();
      }
      if (struct.img != null) {
        oprot.writeFieldBegin(IMG_FIELD_DESC);
        oprot.writeString(struct.img);
        oprot.writeFieldEnd();
      }
      if (struct.outDate != null) {
        oprot.writeFieldBegin(OUT_DATE_FIELD_DESC);
        oprot.writeString(struct.outDate);
        oprot.writeFieldEnd();
      }
      if (struct.Developers != null) {
        oprot.writeFieldBegin(DEVELOPERS_FIELD_DESC);
        oprot.writeString(struct.Developers);
        oprot.writeFieldEnd();
      }
      if (struct.diyLabels != null) {
        oprot.writeFieldBegin(DIY_LABELS_FIELD_DESC);
        oprot.writeString(struct.diyLabels);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GameTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public GameTupleScheme getScheme() {
      return new GameTupleScheme();
    }
  }

  private static class GameTupleScheme extends org.apache.thrift.scheme.TupleScheme<Game> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Game struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetGameId()) {
        optionals.set(0);
      }
      if (struct.isSetGameName()) {
        optionals.set(1);
      }
      if (struct.isSetCommentsNum()) {
        optionals.set(2);
      }
      if (struct.isSetLikeRate()) {
        optionals.set(3);
      }
      if (struct.isSetDiscount()) {
        optionals.set(4);
      }
      if (struct.isSetPrice()) {
        optionals.set(5);
      }
      if (struct.isSetImg()) {
        optionals.set(6);
      }
      if (struct.isSetOutDate()) {
        optionals.set(7);
      }
      if (struct.isSetDevelopers()) {
        optionals.set(8);
      }
      if (struct.isSetDiyLabels()) {
        optionals.set(9);
      }
      oprot.writeBitSet(optionals, 10);
      if (struct.isSetGameId()) {
        oprot.writeString(struct.gameId);
      }
      if (struct.isSetGameName()) {
        oprot.writeString(struct.gameName);
      }
      if (struct.isSetCommentsNum()) {
        oprot.writeI32(struct.commentsNum);
      }
      if (struct.isSetLikeRate()) {
        oprot.writeString(struct.LikeRate);
      }
      if (struct.isSetDiscount()) {
        oprot.writeString(struct.discount);
      }
      if (struct.isSetPrice()) {
        oprot.writeString(struct.price);
      }
      if (struct.isSetImg()) {
        oprot.writeString(struct.img);
      }
      if (struct.isSetOutDate()) {
        oprot.writeString(struct.outDate);
      }
      if (struct.isSetDevelopers()) {
        oprot.writeString(struct.Developers);
      }
      if (struct.isSetDiyLabels()) {
        oprot.writeString(struct.diyLabels);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Game struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(10);
      if (incoming.get(0)) {
        struct.gameId = iprot.readString();
        struct.setGameIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.gameName = iprot.readString();
        struct.setGameNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.commentsNum = iprot.readI32();
        struct.setCommentsNumIsSet(true);
      }
      if (incoming.get(3)) {
        struct.LikeRate = iprot.readString();
        struct.setLikeRateIsSet(true);
      }
      if (incoming.get(4)) {
        struct.discount = iprot.readString();
        struct.setDiscountIsSet(true);
      }
      if (incoming.get(5)) {
        struct.price = iprot.readString();
        struct.setPriceIsSet(true);
      }
      if (incoming.get(6)) {
        struct.img = iprot.readString();
        struct.setImgIsSet(true);
      }
      if (incoming.get(7)) {
        struct.outDate = iprot.readString();
        struct.setOutDateIsSet(true);
      }
      if (incoming.get(8)) {
        struct.Developers = iprot.readString();
        struct.setDevelopersIsSet(true);
      }
      if (incoming.get(9)) {
        struct.diyLabels = iprot.readString();
        struct.setDiyLabelsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

